SET(LIB_OMEGA_MASTER_SRC )
SET(LIB_OMEGA_MASTER_INC dhdc.h drdc.h)

SET(CMAKe_AUTOMOC ON)
SET(CMAKE_AUTORCC ON)
SET(CMAKE_AUTOUIC ON)

#ADD_LIBRARY(omega_static STATIC ${LIB_OMEGA_MASTER_SRC} ${LIB_OMEGA_MASTER_INC} )
#SET_TARGET_PROPERTIES(omega_static PROPERTIES OUTPUT_NAME "omega_master")
#TARGET_LINK_LIBRARIES(peripheral_static PUBLIC ${QtComponents})

#ADD_LIBRARY(omega_master SHARED ${LIB_OMEGA_MASTER_SRC} ${LIB_OMEGA_MASTER_INC})
#SET_TARGET_PROPERTIES(omega_master PROPERTIES OUTPUT_NAME "omega_master")
#TARGET_LINK_LIBRARIES(peripheral_device PUBLIC ${QtComponents})